$(document).ready(function(){
var cnt = 2;
$("#anc_add").click(function(){
$('#dataTable tr').last().after('<span style="color:#60140A;"><div><input type="checkbox" required="required" name="chk[]" checked="checked" /></div><br>Name: <input type="text" name="ud_fname[]" maxlength="100" style="width: 100px" /> Age: <input type="number" name="ud_fage[]" style="width: 40px" />
 Relation: <select name="ud_frelation[]"><option value=""></option><option value="Mother">Mother</option><option value="Father">Father</option><option value="Elder Brother">Elder Brother</option><option value="Elder Sister">Elder Sister</option><option value="Younger Brother">Younger Brother</option><option value="Younger Sister">Younger Sister</option><option value="Grand Father">Grand Father</option><option value="Grand Mother">Grand Mother</option><option value="Uncle">Uncle</option><option value="Aunt">Aunt</option><option value="Cousin Brother">Cousine Brother</option><option value="Cousin Sister">Cousin Sister</option><option value="Other">Other</option></select>
 Education: <select name="ud_fedu[]"><option value=""></option></option><option value="No School Yet">No School Yet</option><option value="Primary School">Primary School</option><option value="Secondary School">Secondary School</option><option value="Higher Secondary School">Higher Secondary School</option><option value="SSC Pass">SSC Pass</option><option value="SSC Fail">SSC Fail</option><option value="HSC Pass">HSC Pass</option><option value="HSC Fail">HSC Fail</option><option value="Diploma">Diploma</option><option value="Diploma Fail">Diploma Fail</option><option value="Under Graduate">Under Graduate</option><option value="Graduate">Graduate</option><option value="Uneducated">Uneducated</option></select><br><br>
Occupation: <select name="ud_foccu[]"><option value=""></option><option value="Self-employed">Self-employed</option><option value="Private Service">Private Service</option><option value="Govt Service">Government Service</option><option value="Casual Labor">Casual Labor</option><option value="Skilled Labor">Skilled Labor</option><option value="Unskilled Labor">Unskilled Labor</option><option value="Domestic Help">Domestic Help</option><option value="Driver">Driver</option><option value="Housewife">Housewife</option><option value="Unemployed">Unemployed</option></select>
 Income: <select name="ud_fincome[]"><option value=""></option><option value="No Income">No Income</option><option value="Less than 5000 pm">Less than 5000 pm</option><option value="5000 to 10000 pm">5000 to 10000 pm</option><option value="10001 to 20000 pm">10001 to 20000 pm</option><option value="More than 20000 pm">More than 20000 pm</option></select>
 Remarks: <input type="text" name="ud_fremark[]" style="width: 160px;" /><br></span><br><hr size="1"><br>
<span style="color:#60140A; font-family:kiran;font-size:20px;">naava: <button type="button" title="Click here for keyboard support for Marathi typing" onclick="hideshowkeyboard(cnt);"><img src="images/keyboard.png"></button> <input type="text" name="ud_mfname[]" maxlength="100" style="font-family:kiran;font-size:20px;width:210px" id="txt'+cnt+'" onclick="getmytxtid(cnt);"/>
 naataM: <select name="ud_mfrelation[]" style="font-family:kiran;font-size:20px;"><option value=""></option><option value="Aa[-">Aa[-</option><option value="vaiDla">vaiDla</option><option value="maaoza Baa{]">maaoza Baa{]</option><option value="maaozI baihNa">maaozI baihNa</option><option value="CaoTa Baa{]">CaoTa Baa{]</option><option value="CaoTI baihNa">CaoTI baihNa</option><option value="Aajaaobaa">Aajaaobaa</option><option value="AajaI">AajaI</option><option value="kxakxa">kxakxa</option><option value="kxakUx">kxakUx</option><option value="caulata Baa{]">caulata Baa{]</option><option value="caulata baihNa">caulata baihNa</option><option value="[tar">[tar</option></select>
 iSaXaNa: <select name="ud_mfedu[]" style="font-family:kiran;font-size:20px;"><option value=""></option><option value="AjaUna SaaLota jaata naahI">AjaUna SaaLota jaata naahI</option><option value="pa`aqaimakx iSaXaNa">pa`aqaimakx iSaXaNa</option><option value="maaQyaimakx iSaXaNa">maaQyaimakx iSaXaNa</option><option value="{cca maaQyaimakx iSaXaNa">{cca maaQyaimakx iSaXaNa</option><option value="dhavaI paasa">dhavaI paasa</option><option value="dhavaI naapaasa">dhavaI naapaasa</option><option value="baaravaI paasa">baaravaI paasa</option><option value="baaravaI naapaasa">baaravaI naapaasa</option><option value="padivakxa">padivakxa</option><option value="padivakxa naapaasa">padivakxa naapaasa</option><option value="padvaI ApaUNa-">padvaI ApaUNa-</option><option value="padvaIQar">padvaIQar</option><option value="AiSaiXata">AiSaiXata</option></select><br><br>
vyavasaaya: <select name="ud_mfoccu[]" style="font-family:kiran;font-size:20px;"><option value=""></option><option value="svata:caa vyavasaaya">svata:caa vyavasaaya</option><option value="KaajagaI naaokxrI">KaajagaI naaokxrI</option><option value="sarkxarI naaokxrI">sarkxarI naaokxrI</option><option value="pa`asaMigakx kxamagaar">pa`asaMigakx kxamagaar</option><option value="kuxSala kxamagaar">kuxSala kxamagaar</option><option value="AkuxSala kxamagaar">AkuxSala kxamagaar</option><option value="Garkxama">Garkxama</option><option value="vaahnacaalakx">vaahnacaalakx</option><option value="gaRihNaI">gaRihNaI</option><option value="baoraojagaar">baoraojagaar</option></select>
 {tpanna: <select name="ud_mfincome[]" style="font-family:kiran;font-size:20px;"><option value=""></option><option value="{tpanna naahI">{tpanna naahI</option><option value="drmaha 5000 paoXaa kxmaI">drmaha 5000 paoXaa kxmaI</option><option value="drmaha 5000 tao 10000">drmaha 5000 tao 10000</option><option value="drmaha 10001 tao 20000">drmaha 10001 tao 20000</option><option value="drmaha 20000 paoXaa jaasta">drmaha 20000 paoXaa jaasta</option></select> Saora: <button type="button" title="Click here for keyboard support for Marathi typing" onclick="hideshowkeyboard(cnt++);"><img src="images/keyboard.png"></button> <input type="text" name="ud_mfremark[]" style="font-family:kiran;font-size:20px;width:160px;" id="txt'+cnt+'" onclick="getmytxtid(cnt);"/><br></span><br><hr size="1">
');
cnt++;
});

$("#anc_rem").click(function(){
if($('#dataTable tr').size()>1){
 $('#dataTable tr:last-child').remove();
 }else{
 alert('Can not remove all the family members!');
 }
 });

});